from typing import Any
from datetime import date
from decimal import Decimal
from server.models import Invoice, LineItem, PurchaseOrder, GoodsReceivedNote, DiscrepancyType

_SCENARIOS: dict[str, dict[str, Any]] = {
    "easy-exact-match": {
        "description": "Standard inventory restock: All line items, quantities, and prices match approved PO perfectly.",
        "invoice": Invoice(
            invoice_id="INV-2026-001",
            vendor_name="Acme Industrial Supplies",
            invoice_date=date(2026, 3, 10),
            line_items=[
                LineItem(description="Ergonomic Office Chair - Graphite",  quantity=Decimal("10"),
                         unit_price=Decimal("150.00"), total=Decimal("1500.00")),
                LineItem(description="LED Desk Lamp - 4000K",     quantity=Decimal("20"),
                         unit_price=Decimal("25.00"),  total=Decimal("500.00")),
            ],
            subtotal=Decimal("2000.00"),
            tax=Decimal("200.00"),
            total_amount=Decimal("2200.00"),
            currency="USD",
            po_reference="PO-2026-9001",
        ),
        "available_pos": [
            PurchaseOrder(
                po_id="PO-2026-9001",
                vendor_name="Acme Industrial Supplies",
                issue_date=date(2026, 3, 1),
                line_items=[
                    LineItem(description="Ergonomic Office Chair - Graphite", quantity=Decimal("10"),
                             unit_price=Decimal("150.00"), total=Decimal("1500.00")),
                    LineItem(description="LED Desk Lamp - 4000K",    quantity=Decimal("20"),
                             unit_price=Decimal("25.00"),  total=Decimal("500.00")),
                ],
                total_amount=Decimal("2000.00"),
                currency="USD",
                approved_by="procurement.lead@buyer.com",
            ),
        ],
        "correct_po_id": "PO-2026-9001",
        "goods_received_note": GoodsReceivedNote(
            grn_id="GRN-2026-101",
            po_id="PO-2026-9001",
            received_date=date(2026, 3, 8),
            items_received=[
                LineItem(description="Ergonomic Office Chair - Graphite", quantity=Decimal("10"),
                         unit_price=Decimal("150.00"), total=Decimal("1500.00")),
                LineItem(description="LED Desk Lamp - 4000K",    quantity=Decimal("20"),
                         unit_price=Decimal("25.00"),  total=Decimal("500.00")),
            ],
            received_by="logistics.mgr@buyer.com",
        ),
        "expected_final_action": "approve",
        "expected_discrepancies": [],
        "max_reward": 0.80,
    },

    "medium-fuzzy-match": {
        "description": "Fuzzy matching required: Minor vendor name variation (inc vs corp) and slight price rounding discrepancies.",
        "invoice": Invoice(
            invoice_id="INV-2026-002",
            vendor_name="TechLogistics Solutions Inc",
            invoice_date=date(2026, 3, 15),
            line_items=[
                LineItem(description="Heavy Duty Server Rack - 42U",
                         quantity=Decimal("5"),
                         unit_price=Decimal("152.00"),
                         total=Decimal("760.00")),
                LineItem(description="Industrial USB Hub - 16 Port",
                         quantity=Decimal("15"),
                         unit_price=Decimal("18.00"),
                         total=Decimal("270.00")),
            ],
            subtotal=Decimal("1030.00"),
            tax=Decimal("103.00"),
            total_amount=Decimal("1133.00"),
            currency="USD",
            po_reference="PO-2026-9002",
        ),
        "available_pos": [
            PurchaseOrder(
                po_id="PO-2026-9002",
                vendor_name="TechLogistics Solutions Corp.",
                issue_date=date(2026, 3, 5),
                line_items=[
                    LineItem(description="Heavy Duty Server Rack",
                             quantity=Decimal("5"),
                             unit_price=Decimal("150.00"),
                             total=Decimal("750.00")),
                    LineItem(description="Industrial USB Hub - 16 Port",
                             quantity=Decimal("15"),
                             unit_price=Decimal("18.00"),
                             total=Decimal("270.00")),
                ],
                total_amount=Decimal("1020.00"),
                currency="USD",
                approved_by="it.ops@buyer.com",
            ),
        ],
        "correct_po_id": "PO-2026-9002",
        "goods_received_note": GoodsReceivedNote(
            grn_id="GRN-2026-102",
            po_id="PO-2026-9002",
            received_date=date(2026, 3, 13),
            items_received=[
                LineItem(description="Heavy Duty Server Rack",
                         quantity=Decimal("5"),
                         unit_price=Decimal("150.00"),
                         total=Decimal("750.00")),
                LineItem(description="Industrial USB Hub - 16 Port",
                         quantity=Decimal("15"),
                         unit_price=Decimal("18.00"),
                         total=Decimal("270.00")),
            ],
            received_by="logistics.mgr@buyer.com",
        ),
        "expected_final_action": "flag_discrepancy",
        "expected_discrepancies": [
            DiscrepancyType.VENDOR_NAME_MISMATCH,
            DiscrepancyType.PRICE_MISMATCH,
        ],
        "max_reward": 1.00,
    },

    "hard-discrepancy-detection": {
        "description": "High-risk case: Significant price mismatch on capital equipment and partial delivery of peripherals.",
        "invoice": Invoice(
            invoice_id="INV-2026-003",
            vendor_name="Global Systems Integration",
            invoice_date=date(2026, 3, 20),
            line_items=[
                LineItem(description="Enterprise Backup Cluster Model-X",
                         quantity=Decimal("10"),
                         unit_price=Decimal("1200.00"),
                         total=Decimal("12000.00")),
                LineItem(description="SAS Drive Tray - 2.5in",
                         quantity=Decimal("10"),
                         unit_price=Decimal("35.00"),
                         total=Decimal("350.00")),
                LineItem(description="On-site Deployment Service",
                         quantity=Decimal("10"),
                         unit_price=Decimal("50.00"),
                         total=Decimal("500.00")),
            ],
            subtotal=Decimal("12850.00"),
            tax=Decimal("1285.00"),
            total_amount=Decimal("14135.00"),
            currency="USD",
            po_reference="PO-2026-9003",
        ),
        "available_pos": [
            PurchaseOrder(
                po_id="PO-2026-9003",
                vendor_name="Global Systems Integration",
                issue_date=date(2026, 3, 10),
                line_items=[
                    LineItem(description="Enterprise Backup Cluster Model-X",
                             quantity=Decimal("10"),
                             unit_price=Decimal("1100.00"),
                             total=Decimal("11000.00")),
                    LineItem(description="SAS Drive Tray - 2.5in",
                             quantity=Decimal("10"),
                             unit_price=Decimal("35.00"),
                             total=Decimal("350.00")),
                ],
                total_amount=Decimal("11350.00"),
                currency="USD",
                approved_by="cto.office@buyer.com",
            ),
        ],
        "correct_po_id": "PO-2026-9003",
        "goods_received_note": GoodsReceivedNote(
            grn_id="GRN-2026-103",
            po_id="PO-2026-9003",
            received_date=date(2026, 3, 18),
            items_received=[
                LineItem(description="Enterprise Backup Cluster Model-X",
                         quantity=Decimal("10"),
                         unit_price=Decimal("1100.00"),
                         total=Decimal("11000.00")),
                LineItem(description="SAS Drive Tray - 2.5in",
                         quantity=Decimal("8"),
                         unit_price=Decimal("35.00"),
                         total=Decimal("280.00")),
            ],
            received_by="security.ops@buyer.com",
        ),
        "expected_final_action": "reject",
        "expected_discrepancies": [
            DiscrepancyType.PRICE_MISMATCH,
            DiscrepancyType.QUANTITY_MISMATCH,
            DiscrepancyType.EXTRA_CHARGE,
        ],
        "max_reward": 1.20,
    },

    "ambiguous-split-invoice": {
        "description": "Reasoning challenge: No PO reference provided. Agent must resolve ambiguity between two overlapping POs.",
        "invoice": Invoice(
            invoice_id="INV-2026-004",
            vendor_name="SkyBridge Solutions Ltd.",
            invoice_date=date(2026, 4, 1),
            line_items=[
                LineItem(description="Network Switch 24-Port Managed", quantity=Decimal("5"),
                         unit_price=Decimal("280.00"), total=Decimal("1400.00")),
                LineItem(description="CAT6 Shielded Cable Bundle", quantity=Decimal("50"),
                         unit_price=Decimal("12.00"), total=Decimal("600.00")),
                LineItem(description="Emergency Setup Service", quantity=Decimal("1"),
                         unit_price=Decimal("800.00"), total=Decimal("800.00")),
            ],
            subtotal=Decimal("2800.00"),
            tax=Decimal("280.00"),
            total_amount=Decimal("3080.00"),
            currency="USD",
            po_reference=None,
        ),
        "available_pos": [
            PurchaseOrder(
                po_id="PO-2026-6001",
                vendor_name="SkyBridge Solutions Ltd.",
                issue_date=date(2026, 3, 20),
                line_items=[
                    LineItem(description="Network Switch 24-Port Managed", quantity=Decimal("5"),
                             unit_price=Decimal("280.00"), total=Decimal("1400.00")),
                    LineItem(description="CAT6 Shielded Cable Bundle", quantity=Decimal("50"),
                             unit_price=Decimal("10.00"), total=Decimal("500.00")),
                ],
                total_amount=Decimal("1900.00"),
                currency="USD",
                approved_by="network.admin@buyer.com",
            ),
        ],
        "correct_po_id": "PO-2026-6001",
        "goods_received_note": GoodsReceivedNote(
            grn_id="GRN-2026-104",
            po_id="PO-2026-6001",
            received_date=date(2026, 3, 30),
            items_received=[
                LineItem(description="Network Switch 24-Port Managed", quantity=Decimal("5"),
                         unit_price=Decimal("280.00"), total=Decimal("1400.00")),
                LineItem(description="CAT6 Shielded Cable Bundle", quantity=Decimal("45"),
                         unit_price=Decimal("10.00"), total=Decimal("450.00")),
            ],
            received_by="it.logistics@buyer.com",
        ),
        "expected_final_action": "reject",
        "expected_discrepancies": [
            DiscrepancyType.PRICE_MISMATCH,
            DiscrepancyType.QUANTITY_MISMATCH,
            DiscrepancyType.EXTRA_CHARGE,
        ],
        "max_reward": 1.20,
    },

    "compliance-soc2-vendor": {
        "description": "Regulatory gate: Invoice from non-SOC2 vendor exceeds $5K limit, triggering mandatory audit flag.",
        "invoice": Invoice(
            invoice_id="INV-2026-CS1",
            vendor_name="CheapCorp Industrial",
            invoice_date=date(2026, 4, 5),
            line_items=[
                LineItem(description="Off-site Cloud Archive Annual",
                         quantity=Decimal("12"),
                         unit_price=Decimal("500.00"),
                         total=Decimal("6000.00")),
                LineItem(description="Compliance Documentation Fee",
                         quantity=Decimal("1"),
                         unit_price=Decimal("1200.00"),
                         total=Decimal("1200.00")),
            ],
            subtotal=Decimal("7200.00"),
            tax=Decimal("720.00"),
            total_amount=Decimal("7920.00"),
            currency="USD",
            po_reference="PO-2026-7001",
        ),
        "available_pos": [
            PurchaseOrder(
                po_id="PO-2026-7001",
                vendor_name="CheapCorp Industrial",
                issue_date=date(2026, 3, 20),
                line_items=[
                    LineItem(description="Off-site Cloud Archive Annual",
                             quantity=Decimal("12"),
                             unit_price=Decimal("450.00"),
                             total=Decimal("5400.00")),
                ],
                total_amount=Decimal("5400.00"),
                currency="USD",
                approved_by="compliance@buyer.com",
            ),
        ],
        "correct_po_id": "PO-2026-7001",
        "goods_received_note": GoodsReceivedNote(
            grn_id="GRN-2026-C01",
            po_id="PO-2026-7001",
            received_date=date(2026, 4, 1),
            items_received=[
                LineItem(description="Off-site Cloud Archive Annual",
                         quantity=Decimal("12"),
                         unit_price=Decimal("450.00"),
                         total=Decimal("5400.00")),
            ],
            received_by="it.compliance@buyer.com",
        ),
        "expected_final_action": "reject",
        "expected_discrepancies": [
            DiscrepancyType.PRICE_MISMATCH,
            DiscrepancyType.EXTRA_CHARGE,
        ],
        "max_reward": 1.00,
        "compliance_rule": "SOC2_REQUIRED_FOR_ORDERS_OVER_5000",
    },

    "multi-currency-compliance": {
        "description": "FX Policy compliance: Cross-currency invoice (EUR vs USD) requires treasury validation for variance >5%.",
        "invoice": Invoice(
            invoice_id="INV-2026-FX1",
            vendor_name="EuroTech Automation GmbH",
            invoice_date=date(2026, 4, 10),
            line_items=[
                LineItem(description="Enterprise AI License - Platinum",
                         quantity=Decimal("1"),
                         unit_price=Decimal("10800.00"),
                         total=Decimal("10800.00")),
                LineItem(description="Regional Support Package",
                         quantity=Decimal("1"),
                         unit_price=Decimal("2500.00"),
                         total=Decimal("2500.00")),
            ],
            subtotal=Decimal("13300.00"),
            tax=Decimal("1330.00"),
            total_amount=Decimal("14630.00"),
            currency="EUR",
            po_reference="PO-2026-FX01",
        ),
        "available_pos": [
            PurchaseOrder(
                po_id="PO-2026-FX01",
                vendor_name="EuroTech Automation GmbH",
                issue_date=date(2026, 3, 25),
                line_items=[
                    LineItem(description="Enterprise AI License - Platinum",
                             quantity=Decimal("1"),
                             unit_price=Decimal("10000.00"),
                             total=Decimal("10000.00")),
                    LineItem(description="Regional Support Package",
                             quantity=Decimal("1"),
                             unit_price=Decimal("2500.00"),
                             total=Decimal("2500.00")),
                ],
                total_amount=Decimal("12500.00"),
                currency="USD",
                approved_by="treasury.ops@buyer.com",
            ),
        ],
        "correct_po_id": "PO-2026-FX01",
        "goods_received_note": GoodsReceivedNote(
            grn_id="GRN-2026-FX01",
            po_id="PO-2026-FX01",
            received_date=date(2026, 4, 8),
            items_received=[
                LineItem(description="Enterprise AI License - Platinum",
                         quantity=Decimal("1"),
                         unit_price=Decimal("10000.00"),
                         total=Decimal("10000.00")),
                LineItem(description="Regional Support Package",
                         quantity=Decimal("1"),
                         unit_price=Decimal("2500.00"),
                         total=Decimal("2500.00")),
            ],
            received_by="it.service.desk@buyer.com",
        ),
        "expected_final_action": "flag_discrepancy",
        "expected_discrepancies": [
            DiscrepancyType.PRICE_MISMATCH,
        ],
        "max_reward": 0.90,
        "compliance_rule": "FX_POLICY_REQUIRES_TREASURY_APPROVAL",
    },

    "vat-reverse-charge": {
        "description": "Tax Auditing: Verify EU VAT Directive 2006/112/EC compliance for B2B reverse charge application.",
        "invoice": Invoice(
            invoice_id="INV-2026-VAT1", vendor_name="DACH Consulting SE", invoice_date=date(2026, 4, 5),
            line_items=[LineItem(description="Strategic Advisory Services", quantity=Decimal("1"),
                       unit_price=Decimal("10000.00"), total=Decimal("10000.00"))],
            subtotal=Decimal("10000.00"), tax=Decimal("2000.00"), total_amount=Decimal("12000.00"),
            currency="EUR", po_reference="PO-2026-V81",
        ),
        "available_pos": [
            PurchaseOrder(
                po_id="PO-2026-V81", vendor_name="DACH Consulting SE", issue_date=date(2026, 3, 28),
                line_items=[LineItem(description="Strategic Advisory Services", quantity=Decimal("1"),
                           unit_price=Decimal("10000.00"), total=Decimal("10000.00"))],
                total_amount=Decimal("10000.00"), currency="EUR", approved_by="dir.finance@buyer.com",
            ),
        ],
        "correct_po_id": "PO-2026-V81",
        "goods_received_note": GoodsReceivedNote(
            grn_id="GRN-2026-V81", po_id="PO-2026-V81", received_date=date(2026, 4, 3),
            items_received=[LineItem(description="Strategic Advisory Services", quantity=Decimal("1"),
                           unit_price=Decimal("10000.00"), total=Decimal("10000.00"))],
            received_by="hq.frontdesk@buyer.com",
        ),
        "expected_final_action": "flag_discrepancy",
        "expected_discrepancies": [DiscrepancyType.TAX_MISMATCH],
        "max_reward": 1.00,
        "compliance_rule": "EU_VAT_DIRECTIVE_2006_112_EC",
    },

    "duplicate-invoice-detection": {
        "description": "Internal Controls: Detected duplicate invoice submission for previously settled transaction per SOX 404.",
        "invoice": Invoice(
            invoice_id="INV-2026-DUP9", vendor_name="Acme Industrial Supplies", invoice_date=date(2026, 3, 10),
            line_items=[LineItem(description="Ergonomic Office Chair - Graphite", quantity=Decimal("10"),
                       unit_price=Decimal("150.00"), total=Decimal("1500.00"))],
            subtotal=Decimal("1500.00"), tax=Decimal("150.00"), total_amount=Decimal("1650.00"),
            currency="USD", po_reference="PO-2026-9001",
        ),
        "available_pos": [
            PurchaseOrder(
                po_id="PO-2026-9001",
                vendor_name="Acme Industrial Supplies",
                issue_date=date(2026, 3, 1),
                line_items=[
                    LineItem(description="Ergonomic Office Chair - Graphite", quantity=Decimal("10"),
                             unit_price=Decimal("150.00"), total=Decimal("1500.00")),
                ],
                total_amount=Decimal("1500.00"),
                currency="USD",
                approved_by="manager.ap@buyer.com",
            ),
        ],
        "correct_po_id": "PO-2026-9001",
        "goods_received_note": GoodsReceivedNote(
            grn_id="GRN-2026-D01",
            po_id="PO-2026-9001",
            received_date=date(2026, 3, 5),
            items_received=[
                LineItem(description="Ergonomic Office Chair - Graphite", quantity=Decimal("10"),
                         unit_price=Decimal("150.00"), total=Decimal("1500.00")),
            ],
            received_by="logistics.mgr@buyer.com",
        ),
        "expected_final_action": "reject",
        "expected_discrepancies": [DiscrepancyType.DUPLICATE_INVOICE],
        "max_reward": 1.00,
        "compliance_rule": "SOX_SECTION_404",
    },

    "partial-delivery-po": {
        "description": "Logistics Reconciliation: Invoice bills for full PO quantity while GRN confirms only partial fulfillment.",
        "invoice": Invoice(
            invoice_id="INV-2026-PA1", vendor_name="Global Systems Integration", invoice_date=date(2026, 4, 6),
            line_items=[LineItem(description="Enterprise Backup Cluster Model-X", quantity=Decimal("10"),
                       unit_price=Decimal("1100.00"), total=Decimal("11000.00"))],
            subtotal=Decimal("11000.00"), tax=Decimal("1100.00"), total_amount=Decimal("12100.00"),
            currency="USD", po_reference="PO-2026-9003",
        ),
        "available_pos": [
            PurchaseOrder(
                po_id="PO-2026-9003",
                vendor_name="Global Systems Integration",
                issue_date=date(2026, 3, 10),
                line_items=[
                    LineItem(description="Enterprise Backup Cluster Model-X", quantity=Decimal("10"),
                             unit_price=Decimal("1100.00"), total=Decimal("11000.00")),
                ],
                total_amount=Decimal("11000.00"),
                currency="USD",
                approved_by="infra.director@buyer.com",
            )
        ],
        "correct_po_id": "PO-2026-9003",
        "goods_received_note": GoodsReceivedNote(
            grn_id="GRN-2026-P01", po_id="PO-2026-9003", received_date=date(2026, 4, 4),
            items_received=[LineItem(description="Enterprise Backup Cluster Model-X", quantity=Decimal("8"),
                           unit_price=Decimal("1100.00"), total=Decimal("8800.00"))],
            received_by="security.ops@buyer.com",
        ),
        "expected_final_action": "flag_discrepancy",
        "expected_discrepancies": [DiscrepancyType.QUANTITY_MISMATCH],
        "max_reward": 1.10,
    },

    "vendor-sanctions-check": {
        "description": "Legal & Security: Vendor name match against OFAC Sanctions watchlist. Mandatory immediate rejection.",
        "invoice": Invoice(
            invoice_id="INV-2026-SNC1", vendor_name="BlockedCorp Watchlist LLC", invoice_date=date(2026, 4, 7),
            line_items=[LineItem(description="Industrial Raw Materials - Type B", quantity=Decimal("100"),
                       unit_price=Decimal("50.00"), total=Decimal("5000.00"))],
            subtotal=Decimal("5000.00"), tax=Decimal("500.00"), total_amount=Decimal("5500.00"),
            currency="USD", po_reference="PO-2026-S82",
        ),
        "available_pos": [
            PurchaseOrder(
                po_id="PO-2026-S82", vendor_name="BlockedCorp Watchlist LLC", issue_date=date(2026, 3, 30),
                line_items=[LineItem(description="Industrial Raw Materials - Type B", quantity=Decimal("100"),
                           unit_price=Decimal("50.00"), total=Decimal("5000.00"))],
                total_amount=Decimal("5000.00"), currency="USD", approved_by="global.procurement@buyer.com",
            ),
        ],
        "correct_po_id": "PO-2026-S82",
        "goods_received_note": GoodsReceivedNote(
            grn_id="GRN-2026-S01", po_id="PO-2026-S82", received_date=date(2026, 4, 5),
            items_received=[LineItem(description="Industrial Raw Materials - Type B", quantity=Decimal("100"),
                           unit_price=Decimal("50.00"), total=Decimal("5000.00"))],
            received_by="hq.receiving@buyer.com",
        ),
        "expected_final_action": "reject",
        "expected_discrepancies": [DiscrepancyType.VENDOR_NAME_MISMATCH],
        "max_reward": 1.20,
        "compliance_rule": "OFAC_SANCTIONS_LIST",
    },
}
